version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    container_name: app_container
    depends_on:
      - db
    ports:
      - "5001:5000"
    networks:
      - app_network
    restart: unless-stopped
    command: ["/app/wait-for-it.sh", "db", "--", "python", "app.py"]

  db:
    image: "postgres:latest"
    container_name: db_container
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/annagaplanyan/data_engineer_project/db_data
      o: bind

networks:
  app_network:
    driver: bridge
